-- +goose Up
CREATE TABLE "sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "token_hash" bytea UNIQUE NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "sessions" ("user_id");

COMMENT ON COLUMN "sessions"."token_hash" IS 'token''ın sha256 özeti; token''ın kendisi saklanmaz';

-- Kullanıcı adları küçük harfe normalize edilerek saklanır.
UPDATE "users" SET "username" = lower("username");

-- +goose Down
DROP TABLE "sessions";
