-- +goose Up

-- Hatalı giriş sayacı: kullanıcı adı başına 5 hatalı denemede 5 dakika kilit.
-- (Var olmayan kullanıcı adları için de tutulur; böylece hangi adın kayıtlı
-- olduğu kilit davranışından anlaşılamaz.)
CREATE TABLE "login_attempts" (
  "username" varchar PRIMARY KEY,
  "failures" integer NOT NULL DEFAULT 0,
  "locked_until" timestamptz,
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

-- Hesap silme: kullanıcı devre dışı kalır, verileri (işlemler, grup geçmişi) silinmez.
ALTER TABLE "users" ADD COLUMN "deleted_at" timestamptz;
ALTER TABLE "users" ADD COLUMN "password_changed_at" timestamptz;

-- Grup davetleri: davet edilen kabul edene kadar üye olmaz.
CREATE TYPE "invite_status" AS ENUM ('pending', 'accepted', 'declined', 'cancelled');
CREATE TABLE "group_invites" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL REFERENCES "groups" ("id"),
  "inviter_id" integer NOT NULL REFERENCES "users" ("id"),
  "invitee_id" integer NOT NULL REFERENCES "users" ("id"),
  "status" invite_status NOT NULL DEFAULT 'pending',
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "responded_at" timestamptz
);
CREATE UNIQUE INDEX ON "group_invites" ("group_id", "invitee_id") WHERE "status" = 'pending';
CREATE INDEX ON "group_invites" ("invitee_id", "status");

-- Hesaplar arası transfer: iki bacak (çıkan gider + giren gelir) birbirine bağlı.
-- Transferler gelir/gider toplamlarına ve bütçelere sayılmaz.
ALTER TABLE "transactions" ADD COLUMN "transfer_peer_id" integer UNIQUE REFERENCES "transactions" ("id") DEFERRABLE INITIALLY DEFERRED;

-- Aylık kategori bütçeleri.
CREATE TABLE "budgets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "category" varchar(32) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'TRY',
  "amount" bigint NOT NULL CHECK ("amount" > 0),
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);
CREATE UNIQUE INDEX ON "budgets" ("user_id", "category", "currency");

-- Uygulama içi bildirimler (gelen kutusu) ve Web Push abonelikleri.
CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "kind" varchar(32) NOT NULL,
  "title" varchar(160) NOT NULL,
  "body" varchar(400),
  "url" varchar(200),
  "ref_id" integer,
  "read_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);
CREATE INDEX ON "notifications" ("user_id", "created_at" DESC);
-- Aynı olay için tekrar bildirim üretilmesin (örn. aynı ay bütçe aşımı).
CREATE UNIQUE INDEX ON "notifications" ("user_id", "kind", "ref_id") WHERE "ref_id" IS NOT NULL;

CREATE TABLE "push_subscriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "endpoint" text UNIQUE NOT NULL,
  "p256dh" varchar(200) NOT NULL,
  "auth" varchar(100) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);
CREATE INDEX ON "push_subscriptions" ("user_id");

-- Arama için.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX ON "transactions" USING gin (lower(coalesce("description", '') || ' ' || coalesce("counterparty_name", '')) gin_trgm_ops);

-- +goose Down
DROP INDEX IF EXISTS "transactions_lower_idx";
DROP TABLE "push_subscriptions";
DROP TABLE "notifications";
DROP TABLE "budgets";
ALTER TABLE "transactions" DROP COLUMN "transfer_peer_id";
DROP TABLE "group_invites";
DROP TYPE "invite_status";
ALTER TABLE "users" DROP COLUMN "password_changed_at";
ALTER TABLE "users" DROP COLUMN "deleted_at";
DROP TABLE "login_attempts";
