-- +goose Up
CREATE TYPE "transaction_type" AS ENUM (
  'income',
  'expense'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "accounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "currency" varchar(3) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_by" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "group_members" (
  "group_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "joined_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("group_id", "user_id")
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL,
  "group_id" integer,
  "type" transaction_type NOT NULL,
  "amount" bigint NOT NULL CHECK ("amount" > 0),
  "description" varchar,
  "occurred_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "balances" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL,
  "transaction_id" integer UNIQUE NOT NULL,
  "amount" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

-- Index'ler
CREATE UNIQUE INDEX ON "accounts" ("user_id", "name");
CREATE INDEX ON "transactions" ("account_id");
CREATE INDEX ON "transactions" ("group_id");
CREATE INDEX ON "balances" ("account_id", "id");
CREATE INDEX ON "group_members" ("user_id");

COMMENT ON COLUMN "transactions"."amount" IS 'kuruş cinsinden, her zaman pozitif';
COMMENT ON COLUMN "balances"."amount" IS 'işlemden sonraki bakiye, kuruş';

-- Foreign key'ler
ALTER TABLE "accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "groups" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "group_members" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "group_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "transactions" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "transactions" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "balances" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "balances" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id") DEFERRABLE INITIALLY IMMEDIATE;


-- +goose Down
DROP TABLE "balances";
DROP TABLE "transactions";
DROP TABLE "group_members";
DROP TABLE "groups";
DROP TABLE "accounts";
DROP TABLE "users";
DROP TYPE "transaction_type";