-- +goose Up

-- Dekontlar: dosya diskte (RECEIPTS_DIR), burada üst bilgi ve okunan alanlar.
-- status: pending (gelen kutusunda), used (bir işleme bağlandı), dismissed (yok sayıldı).
CREATE TYPE "receipt_status" AS ENUM ('pending', 'used', 'dismissed');

CREATE TABLE "receipts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "storage_key" varchar(64) UNIQUE NOT NULL,
  "mime_type" varchar(64) NOT NULL,
  "size_bytes" integer NOT NULL,
  "sha256" varchar(64) NOT NULL,
  "original_name" varchar,
  "source" varchar(16) NOT NULL DEFAULT 'app',
  "text" text,
  "parsed" jsonb,
  "status" receipt_status NOT NULL DEFAULT 'pending',
  "transaction_id" integer UNIQUE REFERENCES "transactions" ("id") ON DELETE SET NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);
CREATE INDEX ON "receipts" ("user_id", "status");
CREATE UNIQUE INDEX ON "receipts" ("user_id", "sha256");
COMMENT ON COLUMN "receipts"."source" IS 'app (uygulamadan), share (Android paylaş), inbox (iOS Kestirme)';

-- Karşı taraf: giderde alıcı, gelirde gönderen. "Kime gitti" raporu buradan.
ALTER TABLE "transactions"
  ADD COLUMN "counterparty_name" varchar(128),
  ADD COLUMN "counterparty_iban" varchar(34),
  ADD COLUMN "counterparty_bank" varchar(64);
CREATE INDEX ON "transactions" ("counterparty_iban") WHERE "counterparty_iban" IS NOT NULL;

-- Kestirme (iOS) / dış gönderim için kişisel gelen kutusu anahtarı (özeti saklanır).
ALTER TABLE "users" ADD COLUMN "inbox_token_hash" bytea UNIQUE;

-- Görülen tanıtım turları (her yeni özelliğin bir turu var).
ALTER TABLE "users" ADD COLUMN "seen_tours" text[] NOT NULL DEFAULT '{}';

-- +goose Down
ALTER TABLE "users" DROP COLUMN "seen_tours";
ALTER TABLE "users" DROP COLUMN "inbox_token_hash";
DROP INDEX IF EXISTS "transactions_counterparty_iban_idx";
ALTER TABLE "transactions" DROP COLUMN "counterparty_bank", DROP COLUMN "counterparty_iban", DROP COLUMN "counterparty_name";
DROP TABLE "receipts";
DROP TYPE "receipt_status";
