-- +goose Up

-- Hedefe ayrılan / hedeften çekilen paralar. İlerleme artık hesabın tüm
-- bakiyesi değil, bu kayıtların toplamıdır; böylece aynı hesapta birden
-- fazla hedef (araba, tatil...) ayrı ayrı izlenebilir. Hesap bakiyesi değişmez.
CREATE TABLE "goal_contributions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "goal_id" integer NOT NULL REFERENCES "savings_goals" ("id") ON DELETE CASCADE,
  "amount" bigint NOT NULL CHECK ("amount" <> 0),
  "note" varchar,
  "occurred_at" timestamptz NOT NULL DEFAULT (now()),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);
CREATE INDEX ON "goal_contributions" ("goal_id", "occurred_at");
COMMENT ON COLUMN "goal_contributions"."amount" IS 'pozitif: hedefe eklenen, negatif: hedeften çekilen';

ALTER TABLE "savings_goals" ADD COLUMN "icon" varchar(16);

-- Mevcut hedeflerin ilerlemesi kaybolmasın: bugünkü bakiyeyi (hedefle sınırlı) ilk katkı olarak yaz.
INSERT INTO "goal_contributions" ("goal_id", "amount", "note")
SELECT g.id, LEAST(g.target_amount, bal.amount), 'başlangıç'
FROM "savings_goals" g
JOIN LATERAL (
  SELECT b.amount FROM "balances" b
  JOIN "transactions" t ON t.id = b.transaction_id
  WHERE t.account_id = g.account_id
  ORDER BY t.occurred_at DESC, t.id DESC
  LIMIT 1
) bal ON bal.amount > 0;

-- +goose Down
ALTER TABLE "savings_goals" DROP COLUMN "icon";
DROP TABLE "goal_contributions";
