-- +goose Up

-- Grup işlemlerinde her üyenin payı. Bir işlemin payları toplamı işlem tutarına eşittir.
CREATE TABLE "transaction_splits" (
  "transaction_id" integer NOT NULL REFERENCES "transactions" ("id") ON DELETE CASCADE,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "amount" bigint NOT NULL CHECK ("amount" >= 0),
  PRIMARY KEY ("transaction_id", "user_id")
);
CREATE INDEX ON "transaction_splits" ("user_id");

-- Mevcut grup işlemleri için güncel üyeler arasında eşit pay (kalan kuruşlar küçük id'li üyelere).
INSERT INTO "transaction_splits" ("transaction_id", "user_id", "amount")
SELECT t.id, m.user_id,
       t.amount / m.cnt + CASE WHEN m.rn <= t.amount % m.cnt THEN 1 ELSE 0 END
FROM "transactions" t
JOIN (
  SELECT group_id, user_id,
         row_number() OVER (PARTITION BY group_id ORDER BY user_id) AS rn,
         count(*) OVER (PARTITION BY group_id) AS cnt
  FROM "group_members"
) m ON m.group_id = t.group_id
WHERE t.group_id IS NOT NULL;

-- Grup içi borç ödemeleri.
CREATE TABLE "settlements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL REFERENCES "groups" ("id"),
  "from_user_id" integer NOT NULL REFERENCES "users" ("id"),
  "to_user_id" integer NOT NULL REFERENCES "users" ("id"),
  "amount" bigint NOT NULL CHECK ("amount" > 0),
  "currency" varchar(3) NOT NULL,
  "transaction_id" integer UNIQUE REFERENCES "transactions" ("id"),
  "note" varchar,
  "created_by" integer NOT NULL REFERENCES "users" ("id"),
  "occurred_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  CHECK ("from_user_id" <> "to_user_id")
);
CREATE INDEX ON "settlements" ("group_id");
COMMENT ON COLUMN "settlements"."transaction_id" IS 'kaydı ekleyenin hesabına yansıyan işlem (opsiyonel)';

-- Tekrarlayan işlemler (kira, aidat, fatura...).
CREATE TYPE "recurrence_frequency" AS ENUM ('weekly', 'monthly', 'yearly');

CREATE TABLE "recurring_transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL REFERENCES "accounts" ("id"),
  "group_id" integer REFERENCES "groups" ("id"),
  "type" transaction_type NOT NULL,
  "amount" bigint NOT NULL CHECK ("amount" > 0),
  "description" varchar,
  "split" jsonb,
  "frequency" recurrence_frequency NOT NULL,
  "interval_count" integer NOT NULL DEFAULT 1 CHECK ("interval_count" BETWEEN 1 AND 12),
  "anchor_day" integer NOT NULL CHECK ("anchor_day" BETWEEN 1 AND 31),
  "next_run_on" date NOT NULL,
  "end_on" date,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);
CREATE INDEX ON "recurring_transactions" ("account_id");
CREATE INDEX ON "recurring_transactions" ("group_id");
CREATE INDEX ON "recurring_transactions" ("next_run_on") WHERE "active";
COMMENT ON COLUMN "recurring_transactions"."anchor_day" IS 'ayın kaçında; kısa aylarda ay sonuna çekilir';

ALTER TABLE "transactions" ADD COLUMN "recurring_id" integer REFERENCES "recurring_transactions" ("id") ON DELETE SET NULL;
-- Aynı tekrar kuralı aynı tarih için iki kez işlem üretemez.
CREATE UNIQUE INDEX ON "transactions" ("recurring_id", "occurred_at") WHERE "recurring_id" IS NOT NULL;

-- Bakiye artık işlem tarihi sırasına göre hesaplanır (geçmiş tarihli işlem ve düzenleme için).
CREATE INDEX ON "transactions" ("account_id", "occurred_at", "id");

-- Birikim hedefleri; ilerleme bağlı hesabın bakiyesinden hesaplanır.
CREATE TABLE "savings_goals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL REFERENCES "accounts" ("id"),
  "name" varchar NOT NULL,
  "target_amount" bigint NOT NULL CHECK ("target_amount" > 0),
  "target_date" date,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);
CREATE INDEX ON "savings_goals" ("account_id");

-- Mevcut bakiye anlık görüntülerini tarih sırasına göre yeniden hesapla.
UPDATE "balances" b SET "amount" = s.running
FROM (
  SELECT id, (SUM(CASE WHEN type = 'income' THEN amount ELSE -amount END)
              OVER (PARTITION BY account_id ORDER BY occurred_at, id))::bigint AS running
  FROM "transactions"
) s
WHERE b.transaction_id = s.id AND b.amount <> s.running;

-- +goose Down
DROP TABLE "savings_goals";
DROP INDEX IF EXISTS "transactions_account_id_occurred_at_id_idx";
ALTER TABLE "transactions" DROP COLUMN "recurring_id";
DROP TABLE "recurring_transactions";
DROP TYPE "recurrence_frequency";
DROP TABLE "settlements";
DROP TABLE "transaction_splits";
